config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  resources :employees
  resources :sessions, only: [:new, :create ,:destroy]
  resources :attendances, only: [:create]  # AttendancesControllerに関するルートを追加
  delete '/logout', to: 'sessions#destroy', as: :logout
  resources :employees do
    member do
      put 'update_attendance'  
      get 'salary_statement'  # 給与明細表示用のルート
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance_record.rb
# app/models/attendance_record.rb

class AttendanceRecord < ApplicationRecord
  belongs_to :employee

  def calculate_working_hours
    if clock_out_time.present? && clock_in_time.present?
      total_minutes = (self.clock_out_time - self.clock_in_time).to_i / 60
      hours = total_minutes / 60
      minutes = total_minutes % 60
  
      # 追加: calculate_working_hours の結果を確認
      puts "calculate_working_hours の結果: #{ { hours: hours, minutes: minutes } }"
  
      { hours: hours, minutes: minutes }
    else
      { hours: 0, minutes: 0 }
    end
  end
  
  def calculate_salary(hourly_wage)
    working_hours = calculate_working_hours
    today_salary = (working_hours[:hours] * 60 + working_hours[:minutes]) * hourly_wage / 60.0
    today_salary.to_i
  end
end

app/models/employee.rb
# app/models/employee.rb

class Employee < ApplicationRecord
  has_many :attendance_records
  belongs_to :position
  has_one :salary
  validates :name, presence: true
  validates :login_id, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
  validates :bank_account, presence: true # 仮のフィールド名です。実際のものに置き換えてください。
  
  def hourly_wage
    # 実際のコードを追加してください
    position.hourly_rate
  end

  def calculate_salary(attendance_record)
    working_hours = attendance_record.calculate_working_hours
    (working_hours * hourly_wage).round(2)
  end
end

app/models/position.rb
class Position < ApplicationRecord
  has_many :employees
  validates :name, presence: true
  validates :hourly_rate, presence: true, numericality: { greater_than: 0 }
end

app/models/salary.rb
class Salary < ApplicationRecord
  belongs_to :employee
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :employee
end

app/controllers/application_controller.rb
# app/controllers/application_controller.rb

class ApplicationController < ActionController::Base
  include SessionsHelper
  protect_from_forgery with: :exception
  # before_action :check_authentication

  private

  # def check_authentication
  #   puts current_employee.inspect
  #   unless current_employee
  #     redirect_to new_session_path
  #   end
  # end
end

app/controllers/attendances_controller.rb
# app/controllers/attendances_controller.rb

class AttendancesController < ApplicationController
  def create
    employee = Employee.find(params[:employee_id])
    attendance = AttendanceRecord.new(employee: employee, clock_in_time: Time.current)

    if attendance.save
      redirect_to employee_path(employee), notice: '出勤しました。'
    else
      redirect_to employee_path(employee), alert: '出勤できませんでした。'
    end
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show]

  def index
    # トップ画面の表示に必要な処理を記述
    @employees = Employee.all
  end

  def new
    @employee = Employee.new
  end

  def show
    @employee = current_employee
  end

  def create
    @employee = Employee.new(employee_params)

    if @employee.save
      redirect_to employees_path, notice: 'Employee was successfully created.'
    else
      render :new
    end
  end

  def update_attendance
    # 退勤時の処理をここに追加
    employee = Employee.find(params[:id])
    attendance_record = employee.attendance_records.last
    if attendance_record.present?
        attendance_record.clock_out_time = Time.current
        working_hours = attendance_record.calculate_working_hours
        print "退勤時間のところ + #{working_hours[:minutes]}"
        attendance_record.update(
          clock_out_time: attendance_record.clock_out_time,
          work_date: Date.current,
          working_hours: working_hours[:hours] * 60 + working_hours[:minutes]
        )
        puts "working_hours after: #{attendance_record.working_hours}"
        puts "clock_out_time after: #{attendance_record.clock_out_time}"
        redirect_to employee_path(employee), notice: '退勤しました。'
    end
  end

  def salary_statement
    @employee = Employee.find(params[:id])
    @attendance_records = @employee.attendance_records.where("strftime('%m', work_date) = ?", Date.current.strftime('%m'))
    @total_working_hours = calculate_total_working_hours(@attendance_records)
    @hourly_wage = @employee.position.hourly_rate
    @total_salary = calculate_total_salary(@total_working_hours, @hourly_wage)

    render 'salary_statement'
  end

  private

  def calculate_total_working_hours(attendance_records)
    total_hours = attendance_records.sum do |record|
      record.calculate_working_hours[:hours]
    end
    total_minutes = attendance_records.sum do |record|
      record.calculate_working_hours[:minutes]
    end
  
    { hours: total_hours, minutes: total_minutes }
  end

  def calculate_total_salary(total_working_hours, hourly_wage)
    total_minutes = total_working_hours[:hours] * 60 + total_working_hours[:minutes]
    total_salary = total_minutes * hourly_wage / 60.0
    total_salary.to_i
  end

  private

  def employee_params
    params.require(:employee).permit(:name, :email, :login_id, :password, :position_id, :bank_account)
  end

  private

  def set_employee
    @employee = Employee.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @session = Session.new
  end

  def create
    if params[:session].present?
      employee = Employee.find_by(login_id: params[:session][:login_id])      
      if employee
        log_in employee
        puts "ここ通った1"
        redirect_to employee_path(employee), notice: 'ログイン成功しました。'
      else
        flash.now[:danger] = 'ログインIDかパスワードが間違っています'
        @errorMessage = flash.now[:danger]
        puts "ここ通った2"
        render 'new'
      end
    else
      flash.now[:danger] = 'ログインIDかパスワードが間違っています'
      @errorMessage = flash.now[:danger]
      puts "ここ通った3"
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    puts '==== After log_out ===='
    puts "session[:employee_id]: #{session[:employee_id]}"
    puts "@current_employee: #{@current_employee}"
    redirect_to new_session_path, notice: 'ログアウトしました。'
  end
  
  def log_out
    session.delete(:employee_id)  # セッションからユーザーの情報を削除
    @current_employee = nil  # ユーザー情報をクリア
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/sessions_helper.rb
# app/helpers/sessions_helper.rb

module SessionsHelper
  def log_in(employee)
    session[:employee_id] = employee.id
    @current_employee = employee  # @current_employee にも設定
    Rails.logger.debug "User logged in successfully: #{employee.login_id}"
  end

  def log_out
    session.delete(:employee_id)
    @current_employee = nil
  end

  def current_employee
    @current_employee ||= Employee.find_by(id: session[:employee_id])
    Rails.logger.debug "Current employee: #{@current_employee&.login_id}"
    @current_employee
  end

  def logged_in?
    !current_employee.nil?
  end
end

app/views/employees/index.html.erb
<h1>ユーザー一覧</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <!-- 他のカラムも追加 -->
    </tr>
  </thead>
  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= employee.email %></td>
        <!-- 他のカラムも追加 -->
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to 'ログインへ', new_session_path, method: :get %>

app/views/employees/new.html.erb
<!-- app/views/employees/new.html.erb -->

<h1>新規従業員登録</h1>
<%= form_with(model: @employee, url: employees_path, method: :post) do |form| %>
  <p>名前</p>
  <% form.label :name %>
  <%= form.text_field :name %>

  <p>メールアドレス</p>
  <% form.label :email %>
  <%= form.text_field :email %>

  <p>ログインID</p>
  <% form.label :login_id %>
  <%= form.text_field :login_id %>

  <p>パスワード</p>
  <% form.label :password %>
  <%= form.password_field :password %>

  <p>雇用形態</p>
  <% form.label :position %>
  <%= form.collection_select :position_id, Position.all, :id, :name %>

  <p>振込先番号</p>
  <% form.label :bank_account %>
  <%= form.text_field :bank_account %>

  <%= form.submit "従業員の作成" %>
<% end %>

<%= link_to "一覧へ", employees_path, class: "btn btn-primary" %>

app/views/employees/salary_statement.html.erb
<!-- app/views/employees/salary_statement.html.erb -->

<h1>給与明細</h1>

<%= render partial: 'shared/salary_details', locals: { total_working_hours: @total_working_hours, hourly_wage: @hourly_wage, total_salary: @total_salary } %>

<%= link_to '戻る', employee_path(@employee) %>

app/views/employees/show.html.erb
<!-- app/views/employees/show.html.erb -->
<%= button_to 'ログアウト', logout_path, method: :delete %>
<h1>ようこそ <%= @employee.name %></h1>
<p>属性: <%= @employee.position.name %></p>
<p>時給: <%= @employee.position.hourly_rate %></p>

<table>
  <thead>
    <tr>
      <th>項目</th>
      <th>入力/記録</th>
    </tr>
  </thead>
  <tbody>
    <!-- 出勤ボタン -->
    <tr>
      <td>出勤</td>
      <td><%= button_to '出勤', attendances_path, method: :post, params: { action_type: 'start', employee_id: @employee.id } %></td>
    </tr>

    <!-- 退勤ボタン -->
    <tr>
      <td>退勤</td>
      <td><%= button_to '退勤', update_attendance_employee_path(@employee), method: :put %></td>
    </tr>

    <!-- 出社時間 -->
    <tr>
      <td>出社時間</td>
      <td>
        <% if @employee.attendance_records.last.present? %>
          <%= @employee.attendance_records.last.clock_in_time.strftime('%H:%M:%S') %>
        <% else %>
          未出社
        <% end %>
      </td>
    </tr>

    <!-- 退社時間 -->
    <tr>
      <td>退社時間</td>
      <td>
        <% if @employee.attendance_records.last.present? && @employee.attendance_records.last.clock_out_time.present? %>
          <%= @employee.attendance_records.last.clock_out_time.strftime('%H:%M:%S') %>
        <% else %>
          未退社
        <% end %>
      </td>
    </tr>

    <!-- 労働時間 -->
    <tr>
      <td>労働時間</td>
      <td>
        <% if @employee.attendance_records.last.present? && @employee.attendance_records.last.clock_out_time.present? %>
          <% working_minutes = @employee.attendance_records.last.calculate_working_hours[:hours] * 60 + @employee.attendance_records.last.calculate_working_hours[:minutes] %>
          <%= "%02d時間%02d分" % [working_minutes / 60, working_minutes % 60] %>
        <% else %>
          未計算
        <% end %>
      </td>
    </tr>

    <!-- 給与 -->
    <tr>
      <td>給与</td>
      <td>
        <% if @employee.attendance_records.last.present? && @employee.attendance_records.last.clock_out_time.present? %>
          <%= @employee.attendance_records.last.calculate_salary(@employee.hourly_wage) %> 円
        <% else %>
          未計算
        <% end %>
      </td>
    </tr>
  </tbody>
</table>

<%= link_to '給与明細', salary_statement_employee_path(@employee), method: :get %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YourProjectName</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_salary_details.html.erb
<!-- app/views/shared/_salary_details.html.erb -->

<p>合計勤務時間: <%= @total_working_hours[:hours] %> 時間 <%= @total_working_hours[:minutes] %> 分</p>
<p>時給: <%= @hourly_wage %> 円</p>
<p>合計給与額: <%= @total_salary %> 円</p>